name: Pantheon - wait for deployment
inputs:
  pantheon_site_machine_name:
    description: ' '
    required: true

  target_env:
    description: ' '
    required: true
runs:
    using: 'composite'
    steps:

      - name: ⏳ Wait for Pantheon Deployment
        id: wait_for_deployment
        shell: bash
        env:
          EXPECTED_SHA: ${{ github.event.pull_request.head.sha }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          INPUT_TARGET_ENV: ${{ inputs.target_env }}
          INPUT_PANTHEON_SITE_NAME: ${{ inputs.pantheon_site_machine_name }}
        run: |
          terminus workflow:wait ${INPUT_PANTHEON_SITE_NAME}.${INPUT_TARGET_ENV}  --commit=$EXPECTED_SHA --max=1200
